update ins_delt / sync

diff --git a/00.Installation/package/libtorrent-rasterbar/install b/00.Installation/package/libtorrent-rasterbar/install
--- a/00.Installation/package/libtorrent-rasterbar/install
+++ b/00.Installation/package/libtorrent-rasterbar/install
@@ -75,7 +75,7 @@ trap cancel SIGINT
 
 [[ -z $MAXCPUS ]] && MAXCPUS=$(nproc)
 
-# Transform version to branch (used for git clone tag)  [[ $version == 1.1.11 ]] && branch=libtorrent_1_1_11
+# Transform version to branch (used for git clone tag)
 echo $version | grep -qEo "[012]\.[0-9]+\.[0-9]+" && branch=$( echo libtorrent-$version | sed "s/\./_/g" )
 [[ $version == 1.1.11 ]] && branch=libtorrent_1_1_11
 [[ $version == 1.1.12 ]] && branch=libtorrent_1_1_12
@@ -107,9 +107,8 @@ rm -f $HOME/.lt.git.tag ; }
 
 # Install build dependencies for libtorrent-rasterbar
 function install_lt_dependencies() {
-
     echo >> $OutputLOG
-    status_lock=ltd
+    status_lock=$AppNameLower-d
     rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock
 
     apt_install \
@@ -119,7 +118,7 @@ function install_lt_dependencies() {
                   libboost-python-dev                                                                 \
                   zlib1g-dev >> $OutputLOG 2>&1 && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
 
-    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/libtorrent-rasterbar.dependencies.lock
+    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.dependencies.lock
     echo >> $OutputLOG
 }
 
@@ -131,16 +130,18 @@ function install_lt_dependencies() {
 function install_lt_source() {
 
 echo >> $OutputLOG
-status_lock=lt-rasterbar
+status_lock=$AppNameLower
 rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock
 
-[[ -d libtorrent-rasterbar-$version ]] && rm -rf libtorrent-rasterbar-$version
-git clone --depth=1 -b $branch $git_repo libtorrent-rasterbar-$version >> $OutputLOG 2>&1
-cd libtorrent-rasterbar-$version
+[[ -d libtorrent-rasterbar-$version ]] && rm -rf $AppNameLower-$version
+git clone --depth=1 -b $branch $git_repo $AppNameLower-$version >> $OutputLOG 2>&1
+cd $AppNameLower-$version
 
 # See here for details: https://github.com/qbittorrent/qBittorrent/issues/6383
 # Patches from amefs (QuickBox Dev)
-if version_ge $version 1.1 ; then
+if version_ge $version 1.2 ; then
+    sleep 0 ####### wait
+elif version_ge $version 1.1 ; then
     wget https://github.com/QuickBox/QB/raw/master/setup/sources/libtorrent-rasterbar-RC_1_1.patch >> $OutputLOG 2>&1
     patch -p1 < libtorrent-rasterbar-RC_1_1.patch >> $OutputLOG 2>&1
 elif version_ge $version 1.0 ; then
@@ -164,22 +165,22 @@ fi
 # version=$(cat Makefile | grep -i package_version\ \= | cut -d= -f2 | sed 's/ //g')      # From Swizzin
 
 make -j$MAXCPUS  >> $OutputLOG 2>&1
-rm -rf $SCLocation/tmp-libtorrent-rasterbar
-make install     DESTDIR=$SCLocation/tmp-libtorrent-rasterbar  >> $OutputLOG 2>&1
+rm -rf $SCLocation/tmp-$AppNameLower
+make install     DESTDIR=$SCLocation/tmp-$AppNameLower  >> $OutputLOG 2>&1
 mv $SCLocation/tmp-libtorrent-rasterbar/usr/local/lib/python2.7/site-packages  $SCLocation/tmp-libtorrent-rasterbar/usr/local/lib/python2.7/dist-packages
 
 if [[ -n $(which fpm) ]]; then
-    fpm -f -C $SCLocation/tmp-libtorrent-rasterbar -s dir -t deb -n libtorrent-rasterbar --version $version \
-        -p $DebLocation/libtorrent-rasterbar-$version-$CODENAME-$arch.deb \
+    fpm -f -C $SCLocation/tmp-$AppNameLower -s dir -t deb -n $AppNameLower --version $version \
+        -p $DebLocation/$AppNameLower-$version-$CODENAME-$arch.deb \
         --description "an efficient feature complete C++ bittorrent implementation, installed by inexistence" >> $OutputLOG 2>&1
-    dpkg -i $DebLocation/libtorrent-rasterbar-$version-$CODENAME-$arch.deb >> $OutputLOG 2>&1 && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
+    dpkg -i $DebLocation/$AppNameLower-$version-$CODENAME-$arch.deb >> $OutputLOG 2>&1 && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
 else
     make install >> $OutputLOG 2>&1 && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
 fi
 
 echo >> $OutputLOG
-[[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/libtorrent-rasterbar.lock
-[[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/libtorrent-rasterbar.source.$branch.lock ; }
+[[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.lock
+[[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.source.$branch.lock ; }
 
 
 
@@ -187,18 +188,18 @@ echo >> $OutputLOG
 
 # Install from pre-compiled deb package (libtorrent-rasterbar8, based on RC_1_0 #62c96797a06a024dc17a44931c19afe6f7bd7d6c with python-binding fix)
 function install_lt8_deb() {
+    echo >> $OutputLOG
+    status_lock=$AppNameLower
+    rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock
 
-echo >> $OutputLOG
-status_lock=lt-rasterbar
-rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock
+    [[ $CODENAME == Buster ]] && { echo -e "Error: No libtorrent 1.0.11 deb package for Debian 10, please ust libtorrent 1.1 or later." ; exit 1 ; }
+    wget -O lt.$CODENAME.1.0.11.deb https://raw.githubusercontent.com/Aniverse/inexistence/files/debian.package/libtorrent-rasterbar-1.0.11.$CODENAME.amd64.deb >> $OutputLOG 2>&1
+    dpkg -i lt.$CODENAME.1.0.11.deb >> $OutputLOG 2>&1 && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
 
-[[ $CODENAME == Buster ]] && { echo -e "Error: No libtorrent 1.0.11 deb package for Debian 10, please ust libtorrent 1.1 or later." ; exit 1 ; }
-wget -O lt.$CODENAME.1.0.11.deb https://raw.githubusercontent.com/Aniverse/inexistence/files/debian.package/libtorrent-rasterbar-1.0.11.$CODENAME.amd64.deb >> $OutputLOG 2>&1
-dpkg -i lt.$CODENAME.1.0.11.deb >> $OutputLOG 2>&1 && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
-
-echo >> $OutputLOG
-[[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/libtorrent-rasterbar.lock
-[[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/libtorrent-rasterbar.deb.lock ; }
+    echo >> $OutputLOG
+    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.lock
+    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.deb.lock
+}
 
 
 
@@ -208,27 +209,28 @@ echo >> $OutputLOG
 # libtorrent-rasterbar9, based on RC_1_1 6f1250c6535730897909240ea0f4f2a81937d21a
 # with python-binding fix (from amefs) and #5a48292aefd6ebffd5be6b237081ba2d978a2caa fix (Announce only once to private trackers, by Airium)
 function install_lt9_deb() {
+    echo >> $OutputLOG
+    status_lock=$AppNameLower
+    rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock
 
-echo >> $OutputLOG
-status_lock=lt-rasterbar
-rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock
+    wget -O lt.$CODENAME.1.1.13.deb https://raw.githubusercontent.com/Aniverse/inexistence/files/debian.package/libtorrent-rasterbar-1.1.13.1.$CODENAME.amd64.cpp11.deb >> $OutputLOG 2>&1
+    dpkg -i lt.$CODENAME.1.1.13.deb >> $OutputLOG 2>&1 && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
 
-wget -O lt.$CODENAME.1.1.13.deb https://raw.githubusercontent.com/Aniverse/inexistence/files/debian.package/libtorrent-rasterbar-1.1.13.1.$CODENAME.amd64.cpp11.deb >> $OutputLOG 2>&1
-dpkg -i lt.$CODENAME.1.1.13.deb >> $OutputLOG 2>&1 && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
-
-echo >> $OutputLOG
-[[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/libtorrent-rasterbar.lock
-[[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/libtorrent-rasterbar.deb.lock ; }
+    echo >> $OutputLOG
+    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.lock
+    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.deb.lock
+}
 
 
 
 
 
 function install_lt_dependencies_action() {
-[[ ! -f $LOCKLocation/libtorrent-rasterbar.dependencies.lock ]] && {
-echo -ne "Installing libtorrent-rasterbar build dependencies ..." | tee -a $OutputLOG
-install_lt_dependencies & spinner $!
-check_status ltd | tee -a $OutputLOG ; } ; }
+    [[ ! -f $LOCKLocation/libtorrent-rasterbar.dependencies.lock ]] && {
+        echo -ne "Installing libtorrent-rasterbar build dependencies ..." | tee -a $OutputLOG
+        install_lt_dependencies & spinner $!
+        check_status $AppNameLower-d | tee -a $OutputLOG ; }
+}
 
 
 
@@ -265,7 +267,7 @@ esac
 
 cd ; ldconfig
 
-status_lock=lt-rasterbar
+status_lock=$AppNameLower
 ltver_py=$(python -c "import libtorrent ; print libtorrent.version" 2>1 | grep -oE [0-9]+.[0-9]+.[0-9]+)
 ltver=$(pkg-config --exists --print-errors "libtorrent-rasterbar >= 3.0.0" 2>&1 | awk '{print $NF}' | grep -oE [0-9]+.[0-9]+.[0-9]+)
 
