( deluge/install ) WIP

diff --git a/00.Installation/package/deluge/install b/00.Installation/package/deluge/install
--- a/00.Installation/package/deluge/install
+++ b/00.Installation/package/deluge/install
@@ -3,22 +3,24 @@
 # https://github.com/Aniverse/inexistence
 # Author: Aniverse
 
-script_update=2019.07.11
-script_version=r10023
+script_update=2019.07.15
+script_version=r10024
 
 ################################################################################################ Debug
 
 usage_for_debug() {
     export local_packages=/etc/inexistence/00.Installation
-    rm -f $local_packages/package/deluge/install ; nano $local_packages/package/deluge/install
-    bash /etc/inexistence/00.Installation/package/deluge/install -v 1.3.15
+    export s=$local_packages/package/qbittorrent/install
+    rm -f $s ; nano $s
+    bash $s -v 1.3.15
     bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/package/deluge/install) -v 1.3.15
 }
 
 ################################################################################################ Get options
 
 unset AppName AppNameLower Need_SourceCode pm_action \
-      LogRootPath LogTimes DebLocation SCLocation LOCKLocation OutputLOG
+      LogRootPath LogTimes DebLocation SCLocation LOCKLocation OutputLOG \
+      lt_version version mode debug
 
 function show_usage() { echo " Invalid option $1
 Usage:
@@ -28,16 +30,16 @@ Usage:
 "
 exit 1 ; }
 
-OPTS=$(getopt -o m:v:b: --long "mode:,version:,branch:,logbase:,debug" -- "$@")
+OPTS=$(getopt -o m:v:b:l:d --long "mode:,version:,branch:,logbase:,debug" -- "$@")
 [ $? != 0 ] && show_usage
 eval set -- "$OPTS"
 
 while [ -n "$1" ] ; do case "$1" in
-    -m | --mode    ) mode="$2"     ; shift ; shift ;;
-    -v | --version ) version="$2"  ; shift ; shift ;;
-    -b | --branch  ) branch="$2"   ; shift ; shift ;;
-         --logbase      ) LogTimes="$2" ; shift 2 ;;
-         --debug        ) debug=1       ; shift   ;;
+    -m | --mode         ) mode="$2"     ; shift ; shift ;;
+    -v | --version      ) version="$2"  ; shift ; shift ;;
+    -b | --branch       ) branch="$2"   ; shift ; shift ;;
+    -l | --logbase      ) LogTimes="$2" ; shift 2 ;;
+    -d | --debug        ) debug=1       ; shift   ;;
          --             ) shift         ; break   ;;
 esac ; done
 
@@ -45,6 +47,7 @@ esac ; done
 
 AppName=Deluge
 AppNameLower=deluge
+DebName=deluge # Include deluged, deluge-web, deluge-console and so on
 Need_SourceCode=yes
 pm_action=install
 
@@ -56,68 +59,60 @@ else
 fi
 
 set_variables_log_location
+[[ $debug == 1 ]] && debug_log_location
 
-################################################################################################
+################################################################################################ Set Variables 2
 
-# Check if input version is available
-DeSource="http://download.deluge-torrent.org/source"
-AvailableVersion=$(  wget -qO- $DeSource | grep -o "deluge-[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}\.tar.gz" | sort -uV | grep -o "[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}"  )
-[[ -n $version ]] && [[ -z $( echo $AvailableVersion | grep $version ) ]] && { echo -e "\n${CW} The version you input is not available!\n" ; exit 1 ; }
+lt_version=$(pkg-config --exists --print-errors "libtorrent-rasterbar >= 10086" 2>&1 | awk '{print $NF}' | grep -oE [0-9.]+)
 
+# [[ -z $version ]] && [[ -z $version ]] && [[ -z $mode ]] && version=1.3.15
 [[ -z $mode ]] && [[ -n $version ]] && mode=source
 [[ -z $mode ]] && [[ -n $branch  ]] && mode=source
+[[ -z $mode ]] && echo -e "\n${CW} Installation mode must be specified as apt, deb, deb2, deb3 or source${normal}\n" && cancel
 
-# Check if input branch exists
-[[ -n $branch ]] && [[ -z $( wget -qO- "https://github.com/deluge-torrent/deluge" | grep data-name | cut -d '"' -f2 | grep -P "$branch\b" ) ]] && { echo -e "\n${CW} No such branch!\n" ; exit 1 ; }
-
-[[ -n $version ]] && source_type=release
-[[ -n $branch  ]] && source_type=git     && version=$branch
+[[ $mode == ppa ]] && [[ $DISTRO != Ubuntu ]] && echo -e "${normal}PPA is not support for $DISTRO, change installation mode from ppa to apt" && mode=apt
 
 # Check if ssl issue should be fix
 version_ge $version 1.3.11 || DESSL=Yes
+# Check if input branch is available
+git_repo="https://github.com/deluge-torrent/deluge"
+[[ -n $branch ]] && check_remote_git_repo_branch  $git_repo  $branch
+# Check if input version is available
+DeSource="http://download.deluge-torrent.org/source"
+AvailableVersion=$(  wget -qO- $DeSource | grep -o "deluge-[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}\.tar.gz" | sort -uV | grep -o "[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}"  )
+[[ -n $version ]] && [[ -z $( echo $AvailableVersion | grep $version ) ]] && echo -e "${CW} The version you input is not available!" && exit 1
+
+[[ -n $version ]] && source_type=release
+[[ -n $branch  ]] && source_type=git     # && version=$branch
 
 # Check if libtorrent below 1.1.2 is supported
-version_ge $version  2.0 && export lt8_support=No || lt8_support=Yes
-[[ $branch == develop ]] && export lt8_support=No || lt8_support=Yes
-lt_ver=$( pkg-config --exists --print-errors "libtorrent-rasterbar >= 3.0.0" 2>&1 | awk '{print $NF}' | grep -oE [0-9.]+ )
-[[ -n $lt_ver ]] && version_ge $lt_ver 1.1.3 && lt_ver_newer=Yes || lt_ver_newer=No
-[[ $lt8_support == No ]] && [[ $lt_ver_newer == No ]] && echo -e "\n${CW} libtorrent-rasterbar 1.1.3 and above is required when installing deluge 2.0 and above${normal}\n" && exit 1
+[[ -n $version ]] && version_ge $version 2.0 && version_ge $lt_ver 1.1.3 ||
+{ echo -e "${CW} libtorrent-rasterbar 1.1.3 and later is required when installing deluge 2.0 and above${normal}" && exit 1 ; }
 
-# Random Number
-# [[ $mode =~ (source|alt) ]] && RN=$(shuf -i 1-999 -n1)
-
-
-case $mode in
-    apt     ) sleep 0  ;;
-    ppa     ) sleep 0  ;;
-    source  ) sleep 0  ;;
-    alt     ) sleep 0  ;;
-    ""   | *) echo -e "\n${CW} Installation mode must be specified as apt, ppa, source or alt${normal}\n"   ;;
-esac
-
-################################################################################################
+################################################################################################ Sub Functions
 
 
 
-
-
-# Install build dependencies for deluge 
 function install_deluge_dependencies() {
+    echo >> $OutputLOG
+    status_lock=$AppNameLower-d
+    echo "status_lock=$status_lock" > /tmp/Variables
+    rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock
 
-# Install Dependencies without python-libtorrent (libtorrent-rasterbar should have been built before)
-apt-get install -y python python-twisted python-openssl python-setuptools intltool python-xdg python-chardet geoip-database python-notify python-pygame python-glade2 librsvg2-common xdg-utils python-mako python-pip >> $OutputLOG 2>&1 && touch /tmp/ded.1.lock || touch /tmp/ded.2.lock
+    # Install Dependencies without python-libtorrent (libtorrent-rasterbar should have been built before)
+    apt-get install -y python python-twisted python-openssl python-setuptools python-xdg python-chardet python-notify python-pygame python-glade2  python-mako python-pip \
+    intltool geoip-database librsvg2-common xdg-utils \
+    >> $OutputLOG 2>&1 && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
 
-# This is for deluge 2.0
-pip install --upgrade pip >> $OutputLOG 2>&1
-/usr/local/bin/pip install --upgrade twisted pillow rencode pyopenssl >> $OutputLOG 2>&1
+    # This is for deluge 2.0
+    pip install --upgrade pip >> $OutputLOG 2>&1
+    /usr/local/bin/pip install --upgrade twisted pillow rencode pyopenssl >> $OutputLOG 2>&1
 
-[[ -f /tmp/ded.1.lock ]] && touch $LOCKLocation/deluge.dependencies.lock ; }
+    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.dependencies.lock
+    echo >> $OutputLOG
+}
 
 
-
-
-
-# Fetch source files
 function fetch_source_codes() {
 cd $SCLocation
 if   [[ $source_type == release ]]; then
@@ -131,10 +126,12 @@ elif [[ $source_type ==   git   ]]; then
     git checkout $branch >> $OutputLOG 2>&1
 fi ; }
 
-# Fix older deluged ssl issue
-function deluge_old_version_ssl_fix() {
+
+# Fix old deluged ssl issue
+function deluge_ssl_fix() {
 sed -i "s/SSL.SSLv3_METHOD/SSL.SSLv23_METHOD/g" deluge/core/rpcserver.py
 sed -i "/        ctx = SSL.Context(SSL.SSLv23_METHOD)/a\        ctx.set_options(SSL.OP_NO_SSLv2 & SSL.OP_NO_SSLv3)" deluge/core/rpcserver.py ; }
+
 
 # Install deluged to another path which is $SCLocation/deluge-$version-tmp/bin/deluged
 function deluge_install_diff() {
@@ -152,7 +149,7 @@ function install_deluge_source() {
 
 fetch_source_codes
 
-[[ $DESSL == Yes ]] && { deluge_old_version_ssl_fix && deluge_install_diff ; version_o=$version ; version=1.3.15 && fetch_source_codes ; }
+[[ $DESSL == Yes ]] && { deluge_ssl_fix && deluge_install_diff ; version_o=$version ; version=1.3.15 && fetch_source_codes ; }
 
 python setup.py build >> $OutputLOG 2>&1
 python setup.py install --install-layout=deb --record /etc/inexistence/01.Log/install_deluge_$version.txt >> $OutputLOG 2>&1 && touch /tmp/de.1.lock || touch /tmp/de.2.lock
