ins_qb / switch to use prebuilt deb for Jessie and Stretch

diff --git a/00.Installation/package/qbittorrent/install b/00.Installation/package/qbittorrent/install
--- a/00.Installation/package/qbittorrent/install
+++ b/00.Installation/package/qbittorrent/install
@@ -3,8 +3,8 @@
 # https://github.com/Aniverse/inexistence
 # Author: Aniverse
 
-script_update=2019.08.07
-script_version=r11017
+script_update=2019.09.09
+script_version=r11018
 
 ################################################################################################ Debug
 
@@ -155,6 +155,7 @@ function install_qt_repo() {
 
 function uninstall_qt_repo() {
     apt-get purge -y qtbase5-dev qttools5-dev-tools libqt5svg5-dev >> $OutputLOG 2>&1
+    dpkg -r qt-common >> $OutputLOG 2>&1
     apt-get autoremove -y >> $OutputLOG 2>&1
 }
 
@@ -184,6 +185,14 @@ function qt_set_env() {
 }
 
 
+function qt_set_env_self_deb() {
+    export PKG_CONFIG_PATH=/usr/local/Qt-5.9.8/lib/pkgconfig:$PKG_CONFIG_PATH
+    export PATH=/usr/local/Qt-5.9.8/bin:$PATH
+    qmake -v >> $OutputLOG 2>&1
+}
+
+
+# DEPRECATED
 function add_jessie_list() {
     cat << EOF > /etc/apt/sources.list.d/jessie.list
 deb http://snapshot.debian.org/archive/debian/20190321T212815Z/ jessie main non-free contrib
@@ -198,6 +207,14 @@ EOF
 }
 
 
+function install_qt_deb() {
+    apt-get install -y build-essential libgl1-mesa-dev python3-dev python
+    wget https://sourceforge.net/projects/inexistence/files/deb/$CODENAME/qt-common.5.9.8.$CODENAME.amd64.deb/download -O qt.5.9.8.deb >> $OutputLOG 2>&1 ||
+    { echo -e "${CW} Failed to wget qt deb${normal}" ; exit 1 ; }
+    dpkg -i qt.5.9.8.deb && ldconfig
+}
+
+
 function install_qbittorrent_dependencies() {
     echo >> $OutputLOG
 
@@ -207,9 +224,8 @@ function install_qbittorrent_dependencies() {
         qt_required_version=5.9.0
             if [[ $CODENAME == stretch ]]; then
                 uninstall_qt_repo
-                add_jessie_list
-                install_qt_ppa_trusty
-                qt_set_env
+                install_qt_deb
+                qt_set_env_self_deb
             elif [[ $CODENAME == xenial ]]; then
                 uninstall_qt_repo
                 install_qt_ppa_xenial
@@ -225,9 +241,9 @@ function install_qbittorrent_dependencies() {
     if [[ $CODENAME =~ (bionic|buster) ]]; then
         install_qt_repo
     elif [[ $CODENAME == jessie ]]; then
-        install_qt_ppa_trusty
+        install_qt_deb
         install_gcc_ppa_trusty
-        qt_set_env
+        qt_set_env_self_deb
     fi
 
     status_lock=$AppNameLower-d
