Fix script of wine, mono, rclone

diff --git a/00.Installation/package/wine/install b/00.Installation/package/wine/install
--- a/00.Installation/package/wine/install
+++ b/00.Installation/package/wine/install
@@ -10,8 +10,8 @@ script_version=r10000
 
 usage_for_debug() {
     export local_packages=/etc/inexistence/00.Installation
-    rm -f $local_packages/package/wine/install ; nano $local_packages/package/wine/install
-    bash /etc/inexistence/00.Installation/package/wine/install
+    export s=$local_packages/package/wine/install
+    rm -f $s ; nano $s ; bash $s
     bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/package/wine/install)
 }
 
@@ -20,15 +20,22 @@ usage_for_debug() {
 unset AppName AppNameLower Need_SourceCode pm_action \
       LogRootPath LogTimes DebLocation SCLocation LOCKLocation OutputLOG
 
-function show_usage() { echo " Invalid option $1" ; exit 1 ; }
+function show_usage() { echo " Invalid option $1
+Usage:
+      -v        Specifiy which version to be installed
+      -l        Specifiy LogBase
+      -d        Enable debug mode
+"
+exit 1 ; }
 
-OPTS=$(getopt -al debug,logbase: -- "$@")
+OPTS=$(getopt -o v:l:d -al version:,debug,logbase: -- "$@")
 [ ! $? = 0 ] && show_usage
 eval set -- "$OPTS"
 
 while [ -n "$1" ] ; do case "$1" in
-         --logbase      ) LogTimes="$2" ; shift 2 ;;
-         --debug        ) debug=1       ; shift   ;;
+    -v | --version      ) version="$2"  ; shift 2 ;;
+    -l | --logbase      ) LogTimes="$2" ; shift 2 ;;
+    -d | --debug        ) debug=1       ; shift   ;;
     -- ) shift ; break ;;
 esac ; done
 
@@ -47,6 +54,7 @@ else
 fi
 
 set_variables_log_location
+[[ $debug == 1 ]] && debug_log_location
 
 ################################################################################################
 
@@ -77,6 +85,7 @@ function install_wine() {
     apt-get install -y winehq-stable >> $OutputLOG 2>&1       # --install-recommends
 
     status_lock=$AppNameLower
+    echo "status_lock=$status_lock" > /tmp/Variables
     rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock 
     which wine > /dev/null && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
     [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.lock
